# Generated by Django 4.1.5 on 2024-01-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_article_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
