# Generated by Django 4.1.5 on 2023-02-12 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alert', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedcheck.profile')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedcheck.urls')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='urls',
            field=models.ManyToManyField(through='speedcheck.ProfileUrl', to='speedcheck.urls'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CruxHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clsm', models.FloatField(default=None, null=True)),
                ('clsd', models.FloatField(default=None, null=True)),
                ('lcpm', models.FloatField(default=None, null=True)),
                ('lcpd', models.FloatField(default=None, null=True)),
                ('fidm', models.FloatField(default=None, null=True)),
                ('fidd', models.FloatField(default=None, null=True)),
                ('inpm', models.FloatField(default=None, null=True)),
                ('inpd', models.FloatField(default=None, null=True)),
                ('ttfbm', models.FloatField(default=None, null=True)),
                ('ttfbd', models.FloatField(default=None, null=True)),
                ('fcpm', models.FloatField(default=None, null=True)),
                ('fcpd', models.FloatField(default=None, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedcheck.urls')),
            ],
            options={
                'unique_together': {('url', 'date')},
            },
        ),
    ]
