# Generated by Django 4.1.5 on 2023-04-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speedcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cruxhistory',
            options={'get_latest_by': 'date'},
        ),
    ]
