# Generated by Django 4.1.5 on 2023-04-24 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("speedcheck", "0002_alter_cruxhistory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CruxWeeklyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lastdate", models.DateField()),
                ("clsm", models.FloatField(default=None, null=True)),
                ("clsd", models.FloatField(default=None, null=True)),
                ("lcpm", models.FloatField(default=None, null=True)),
                ("lcpd", models.FloatField(default=None, null=True)),
                ("fidm", models.FloatField(default=None, null=True)),
                ("fidd", models.FloatField(default=None, null=True)),
                ("inpm", models.FloatField(default=None, null=True)),
                ("inpd", models.FloatField(default=None, null=True)),
                ("ttfbm", models.FloatField(default=None, null=True)),
                ("ttfbd", models.FloatField(default=None, null=True)),
                ("fcpm", models.FloatField(default=None, null=True)),
                ("fcpd", models.FloatField(default=None, null=True)),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="speedcheck.urls",
                    ),
                ),
            ],
            options={
                "get_latest_by": "lastdate",
                "unique_together": {("url", "lastdate")},
            },
        ),
    ]
